# Generated by setup_divefuzz_mc.sh -- source it, do not run.
#   source fuzzer/scripts/env.sh
# Machine-specific; not committed to git.
export PATH="/home/ra4ing/.opam/default/bin:/home/ra4ing/workspace/riscv/bin:$PATH"

# litmus7 harness Makefile overrides (all use ?=):
export GCC="riscv64-linux-gnu-gcc"
export LIBGCC="/usr/lib/gcc-cross/riscv64-linux-gnu/13/libgcc.a"
export LIBGCC_EH="/usr/lib/gcc-cross/riscv64-linux-gnu/13/libgcc_eh.a"
export LITMUS7="/home/ra4ing/.opam/default/bin/litmus7"
export LITMUS7_SHARE="/home/ra4ing/.opam/default/share/herdtools7/litmus"
export NEWLIB_SYSROOT="/home/ra4ing/workspace/riscv/riscv64-unknown-elf"   # discovered

# herd7 oracle (DiveFuzz-MC RVWMO model):
export HERD7="/home/ra4ing/.opam/default/bin/herd7"

# spike (reference DUT -- present on this host):
export SPIKE="/home/ra4ing/workspace/riscv/bin/spike"
